apiVersion: v1
kind: Pod
metadata:
  name: sudokube
  labels:
    app: sudokube
spec:
  nodeSelector:
    hardware-type: CPUONLY
   #For a server with GPUs
   #hardware-type: NVIDIAGPU 
  containers:
  - name:  sudokube
    image: sachinbjohn/kube-base:latest
    workingDir: /var/data
    command:
      - "/usr/sbin/sshd"
      - "-De"
    volumeMounts:
      - mountPath: /var/data
        name: site-data
    ports:
          - containerPort: 2222
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: data-scratch
---
kind: Service 
apiVersion: v1 
metadata:
  name: sudokube-service 
spec:
  type: NodePort
  selector:
    app: sudokube
  ports:
    - nodePort: 27109
      port: 2222 
      targetPort: 2222

